"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

This settings module supports env-driven configuration for DEBUG, SECRET_KEY,
and database selection with a SQLite fallback. No third-party env parser is used.
"""

import os
from urllib.parse import urlparse
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment with sensible default for local development.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-0ku_as45vs5isd^px=t#m8g#^*x7f=w#gw-xb^t@^-pom)r^t6",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Supports values like "1", "true", "True", "yes"
DEBUG = os.environ.get("DEBUG", "true").strip().lower() in {"1", "true", "yes"}

ALLOWED_HOSTS = [
    '.kavia.ai',
    'localhost',
    '127.0.0.1',
    'testserver',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_yasg',
    'corsheaders',
    'api'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


def _db_from_url(db_url: str):
    """
    Parse a database URL into Django DATABASES 'default' dict.
    Supports postgres and sqlite schemes without external dependencies.
    """
    parsed = urlparse(db_url)
    scheme = parsed.scheme

    if scheme.startswith("postgres"):
        # Example: postgres://user:pass@host:5432/dbname
        return {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": (parsed.path or "/").lstrip("/"),
            "USER": parsed.username or "",
            "PASSWORD": parsed.password or "",
            "HOST": parsed.hostname or "",
            "PORT": str(parsed.port or "") if parsed.port else "",
        }
    elif scheme == "sqlite":
        # Example: sqlite:///absolute/path/to/db.sqlite3 or sqlite:///:memory:
        path = parsed.path
        if path in ("/:memory:", ":memory:"):
            name = ":memory:"
        else:
            name = path
            # Ensure absolute path (sqlite:///... -> path begins with /)
            if not name:
                name = str(BASE_DIR / "db.sqlite3")
        return {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": name if name == ":memory:" else name,
        }
    else:
        raise ValueError(f"Unsupported database scheme: {scheme}")


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
DATABASES = {}
_database_url = os.environ.get("DATABASE_URL")
if _database_url:
    try:
        DATABASES["default"] = _db_from_url(_database_url)
    except Exception:
        # Fallback to SQLite if parsing fails
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
else:
    # Allow configuration via discrete POSTGRES_* variables
    pg_name = os.environ.get("POSTGRES_DB")
    pg_user = os.environ.get("POSTGRES_USER")
    pg_password = os.environ.get("POSTGRES_PASSWORD")
    pg_host = os.environ.get("POSTGRES_HOST")
    pg_port = os.environ.get("POSTGRES_PORT")
    if all([pg_name, pg_user, pg_host]):
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": pg_name,
            "USER": pg_user,
            "PASSWORD": pg_password or "",
            "HOST": pg_host,
            "PORT": pg_port or "",
        }
    else:
        # Default to SQLite for local/dev without DB envs
        DATABASES["default"] = {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# CORS and security settings
CORS_ALLOW_ALL_ORIGINS = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
X_FRAME_OPTIONS = 'ALLOWALL'
